spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username= myuser
spring.datasource.password=secret


spring.datasource.url=jdbc:mysql://localhost:52099/mydatabase?createDatabaseIfNotExist=true

spring.jpa.show-sql=false

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=9191

spring.batch.jdbc.initialize-schema=always

#disable job run at startup
spring.batch.job.enabled=false

spring.threads.virtual.enabled=true


# Connection pool — thread sayısına göre ayarla
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

